### ISSUE TITLE
Random NoSuchMethodError after replacing/removing method

### ISSUE THREAD

**Issue by Barteks2x** [dcevm/dcevm#119]
Sometimes when I replace some method with other one or remove existing method, and apply changes (using intellij idea) I get NoSuchMethodError. I couldn't find a reliable way to reproduce it.

It also seems to be generally a bit unstable - sometimes I'm getting exceptions in seemingly unrelated parts of code, or the code misbehaves in way I can't explain (even when all fields have the right values, restarting the JVM fixes the issue).

**Comment by skybber** [comment]
It looks it is not related to DCEVM. Do you have HotswapAgent? What is your tech. stack?

**Comment by Barteks2x** [comment]
I don't have HotswapAgent. I use DCEVM on linux with oracle JVM in MinecraftForge development environment (if that's what this question was about).

**Comment by skybber** [comment]
Could you supply stack trace ? It looks like a problem with reflection cache.

**Comment by Barteks2x** [comment]
I will when I get such issue next time (or find it in old logs). I'm not sure how that would help since it's just java exception... just NoSuchMethodError.

**Comment by Barteks2x** [comment]
I found the NoSuchMethodError stacktrace in log but I still have no idea in what way it could be useful. It's just whatever code was executing that I modified throwing an error:
```
java.lang.NoSuchMethodError: genesis.world.featuretracker.FeatureInfo.getBoundingBox()Lnet/minecraft/world/gen/structure/StructureBoundingBox;
	at genesis.world.featuretracker.FeatureInteractionTracker.isAllowed(FeatureInteractionTracker.java:68)
	at genesis.world.featuretracker.FeatureInteractionTracker.initFeaturesFor(FeatureInteractionTracker.java:47)
	at genesis.world.ChunkGeneratorGenesis.populate(ChunkGeneratorGenesis.java:139)
	at net.minecraft.world.chunk.Chunk.populateChunk(Chunk.java:1069)
	at net.minecraft.world.chunk.Chunk.populateChunk(Chunk.java:1052)
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:160)
	at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:130)
	at net.minecraft.server.management.PlayerChunkMap.tick(PlayerChunkMap.java:178)
	at net.minecraft.world.WorldServer.tick(WorldServer.java:230)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:772)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by skybber** [comment]
Ok, it's better then have information that a NoSuchMethodError occured. Anyway it is really strange. I do a lot of such modifications in another project without any such problems. What version of dcevm and hosting jdk are you using ?

**Comment by Barteks2x** [comment]
`java -version` output:
```
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Dynamic Code Evolution 64-Bit Server VM (build 25.71-b01-dcevmlight-8, mixed mode)
```

**Comment by skybber** [comment]
Its unable to find out the cause of your problems from the information you have supplied. It would be great if you are able to reproduce the bug. Try to remember what kind of changes you did before. Is the class specific in some way (inner classes, lambdas etc)? You can try  JVM option-XX:TraceRedefineClasses=1 to see the redefinition logs as well, me be it can be helpful.

**Comment by Barteks2x** [comment]
I will try that. It's hard to remember exactly what I changed. If this option isn't too spammy I can always run with this until I get this kind of issue again.

I know it has to be in some way reproducible as I actually got it twice in almost the same place.

**Comment by gnom7** [comment]
Have same problem with same DCEVM version.

```
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Dynamic Code Evolution 64-Bit Server VM (build 25.71-b01-dcevmlight-8, mixed mode)
```
Sample code to reproduce.
```
public class DelTest {

    public static void main(String[] args) throws Throwable {
        System.out.println();
        print();
        System.out.println();
    }


    private static void print() {
        System.out.println();
    }

}
```
When I run this in debug mode with breakpoint on first line of `main` method code, then change my method's name from `print` to anything else, then after recompile and successful swap I get 
```
Exception in thread "main" java.lang.NoSuchMethodError: DelTest.print()V
	at DelTest.main(DelTest.java:5)
```
That is all stack trace, with `-XX:TraceRedefineClasses=1` I get
```
RedefineClasses-0x1: Redefinition with revision number 0 started!
RedefineClasses-0x1: loading new class versions (1)
RedefineClasses-0x1: Class being reloaded: DelTest
RedefineClasses-0x1: 1 classes affected
RedefineClasses-0x1: Redefine order: 
RedefineClasses-0x1: DelTest
RedefineClasses-0x1: Processing affected class DelTest (1 of 1)
RedefineClasses-0x1: Comparing different class versions of class DelTest
RedefineClasses-0x1: Super class is java/lang/Object
RedefineClasses-0x1: Linking class 0/1 DelTest
RedefineClasses-0x1: All classes loaded!
RedefineClasses-0x1: Finished verification!
RedefineClasses-0x1: Loaded new class versions!
RedefineClasses-0x1: doit_prologue finished!
RedefineClasses-0x1: Before updating instances
RedefineClasses-0x1: After updating instances
RedefineClasses-0x1: GC Operation epilogue finished!
RedefineClasses-0x1: Redefinition finished!
```
