### ISSUE TITLE
Version for Java 8u121?

### ISSUE THREAD

**Issue by sanity** [dcevm/dcevm#120]
Hi, will there be an updated version for Java 8u121?  This is the current release for OSX, and it doesn't seem particularly easy to find older releases like 112.

Or will the 112 build work with 121 also?

**Comment by skybber** [comment]
8u112 works within 8u121 on Linux at least. Could you check it (and confirm) please on OSX ?

**Comment by sanity** [comment]
Ok, seems to work - although I get the following exception (I'm using it with Kotlin in IntelliJ):
```
HOTSWAP AGENT: 13:48:55.338 ERROR (org.hotswap.agent.annotation.handler.PluginClassFileTransformer) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin' class 'investorscan/web/MainPage$$special$$inlined$instance$2'.
java.lang.reflect.InvocationTargetException
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:189)
 at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:85)
 at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:181)
 at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
 at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
Caused by: java.lang.NullPointerException
 at org.hotswap.agent.plugin.jvm.AnonymousClassInfos.lastModified(AnonymousClassInfos.java:252)
 at org.hotswap.agent.plugin.jvm.AnonymousClassInfos.<init>(AnonymousClassInfos.java:90)
 at org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin.getStateInfo(AnonymousClassPatchPlugin.java:218)
 at org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin.patchAnonymousClass(AnonymousClassPatchPlugin.java:82)
 ... 9 more
```

**Comment by skybber** [comment]
It is HotswapAgent issue, pls push it to HA. btw. dcevm+HA works with Kotlin (WAW) ?

**Comment by sanity** [comment]
Yup, seems to work with Kotlin - at least in my initial testing.

Created issue for HotswapAgent: https://github.com/HotswapProjects/HotswapAgent/issues/180

Now I'm trying to figure out how I can get my web framework to initiate a web page reload when a hotswap occurs.

FYI - here is the web framework I'm building - all help appreciated!  https://github.com/sanity/kweb

**Comment by skybber** [comment]
HotswapAgent issue
