### ISSUE TITLE
there seems to be an issue when trying to install on win 64bit with java 8.0.131 (64bit too)

### ISSUE THREAD

**Issue by alain57** [dcevm/dcevm#125]
java -jar DCEVM-light-8u112.jar
java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Java\jdk1.8.0_131"/..
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.nio.file.Paths.get(Unknown Source)
        at com.github.dcevm.installer.Installer.scanPaths(Installer.java:154)
        at com.github.dcevm.installer.Installer.listInstallations(Installer.java:105)
        at com.github.dcevm.installer.MainWindow.<init>(MainWindow.java:48)
        at com.github.dcevm.installer.Main.main(Main.java:46)

**Comment by diabolusss** [comment]
I have the same issue: windows 7 64bit, {jdk1.7.x, jdk1.8.x}

**Comment by saiteg** [comment]
Simply remove <"> from JAVA_HOME variable

**Comment by diabolusss** [comment]
yeah, thank you. Just found that <"> in JAVA_HOME is the actual reason.
