### ISSUE TITLE
JDWP exit error when using multiple java agents

### ISSUE THREAD

**Issue by ronvanpol** [dcevm/dcevm#142]
I am getting the following error when I try to use DCEVM with multiple java agents:

```
JDWP exit error JVMTI_ERROR_INVALID_THREAD(10): cannot get thread local storage [threadControl.c:195]
FATAL ERROR in native method: JDWP cannot get thread local storage, jvmtiError=JVMTI_ERROR_INVALID_THREAD(10)
	at java.lang.Thread.currentThread(Native Method)
	at java.lang.Thread.interrupted(Thread.java:947)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.checkInterruptWhileWaiting(AbstractQueuedSynchronizer.java:2002)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2079)
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:522)
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:684)
	at sun.nio.fs.AbstractWatchService.poll(AbstractWatchService.java:108)
	at org.hotswap.agent.watch.nio.AbstractNIO2Watcher.processEvents(AbstractNIO2Watcher.java:220)
	at org.hotswap.agent.watch.nio.AbstractNIO2Watcher.access$100(AbstractNIO2Watcher.java:64)
	at org.hotswap.agent.watch.nio.AbstractNIO2Watcher$1.run(AbstractNIO2Watcher.java:289)
Disconnected from server
```
I am trying to combine the hotswap-agent together with another javaagent (for instance xRebel or Stackify). My vm startup parameters are:

-XXaltjvm=dcevm -javaagent:D:\java\hotswap-agent-1.0.jar -javaagent:D:\Stackify\lib\stackify-java-apm.jar

When using a regular VM with multiple agents (hotswap + xrebel/stackify) everything works properly.

**Comment by MaXal** [comment]
Same for me:
```
VirtualMachine virtualMachine = VirtualMachine.attach(OSProcessUtil.getApplicationPid());
virtualMachine.loadAgentPath(getFullLibraryPath(), agentOptions);
```

and I get:
```
Exception in thread "Java2D Queue Flusher" JDWP exit error JVMTI_ERROR_INVALID_THREAD(10): cannot get thread local storage [threadControl.c:195]
JDWP exit error JVMTI_ERROR_INVALID_ENVIRONMENT(116): on getting an object hash code [util.c:1381]
ERROR: JDWP unable to dispose of JVMTI environment: JVMTI_ERROR_INVALID_ENVIRONMENT(116)
FATAL ERROR in native method: JDWP on getting an object hash code, jvmtiError=JVMTI_ERROR_INVALID_ENVIRONMENT(116)
	at java.lang.Throwable.printStackTrace(Throwable.java:643)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1061)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1956)
```

**Comment by lepuso** [comment]
Similiar issues with other agents - 
**JDWP exit error JVMTI_ERROR_INVALID_CLASS(21): signature [classTrack.c:235]**

`JDWP exit error JVMTI_ERROR_INVALID_CLASS(21): signature [classTrack.c:235]
FATAL ERROR in native method: JDWP signature, jvmtiError=JVMTI_ERROR_INVALID_CLASS(21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

**Comment by RaymondLam1** [comment]
Are there any fixes?
