### ISSUE TITLE
Error when launching Virgo OSGI Server using DCEVM patched JDK

### ISSUE THREAD

**Issue by Rafaesp** [dcevm/dcevm#144]
Hi, I can't get to work [Virgo](http://www.eclipse.org/virgo/) using DCEVM. It crashes inmediately with the following log message:
```!SESSION Thu May 10 19:58:07 CEST 2018 -----------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2018-05-10 19:58:07.410
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.NoClassDefFoundError: org/eclipse/core/runtime/internal/adaptor/EclipseAdaptorMsg
	at org.eclipse.core.runtime.internal.adaptor.EclipseAdaptorMsg.<clinit>(EclipseAdaptorMsg.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
```
Any idea? Thanks!

**Comment by skybber** [comment]
Could you try to use HotswapAgent [osgi-equinox](https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-osgiequinox-plugin/README.md) plugin? There is also [thread](https://groups.google.com/forum/#!topic/hotswapagent/qo0jXaBoaGg) about HA for eclipse, it could be helpful for your case.

**Comment by Rafaesp** [comment]
My fault! I was using incorrect version of java!
Thanks!
