### ISSUE TITLE
Segfault when redefining classes inside a class transformer

### ISSUE THREAD

**Issue by DaMatrix** [dcevm/dcevm#199]
Calling `Instrumentation#redefineClasses` from inside of `ClassFileTransformer#transform` causes DCEVM to segfault. Moving the call to `redefineClasses` to be executed from a different thread isn't enough to work around it (although it occasionally *does* work), but running it on a different thread with an added delay of a few seconds does work.

[hs_err_pid6162.log](https://github.com/dcevm/dcevm/files/7312668/hs_err_pid6162.log)

The code works on the standard HotSpot VM perfectly fine without having to add any artificial delays.

**Comment by skybber** [comment]
You are using pretty old version. I did not remember if we had hotswap synchronization in devm8.161, could you try TravaOpenJDK or later dcevm versions ?

**Comment by skybber** [comment]
You can find them at https://github.com/TravaOpenJDK/trava-jdk-8-dcevm/releases/tag/dcevm8u282b08

**Comment by DaMatrix** [comment]
> You can find them at https://github.com/TravaOpenJDK/trava-jdk-8-dcevm/releases/tag/dcevm8u282b08

Tested, the crash still occurs. [hs_err_pid17877.log](https://github.com/dcevm/dcevm/files/7313176/hs_err_pid17877.log)

**Comment by DaMatrix** [comment]
I should note that it is very inconsistent - sometimes the crash happens on the VM thread, sometimes it's on the JDWP thread, and the stack dump in the crash log isn't always exactly the same.

**Comment by skybber** [comment]
dcevm11 has the same problem?

**Comment by DaMatrix** [comment]
My program doesn't run in Java >8, so I'll have to see if I can make a minimum reproducible example on that version.

**Comment by DaMatrix** [comment]
Okay, I've tested it on Java 11. It works fine on standard OpenJDK 11 again, but with DCEVM 11 the `JDWP Transport Listener` thread now hangs.

```
"JDWP Transport Listener: dt_socket" #20 daemon prio=10 os_prio=0 cpu=46.37ms elapsed=52.16s tid=0x00007fbaf4519800 nid=0xc6e runnable  [0x00007fbab15ef000]
   java.lang.Thread.State: RUNNABLE
	at sun.instrument.InstrumentationImpl.redefineClasses0(java.instrument@11.0.11/Native Method)
	at sun.instrument.InstrumentationImpl.redefineClasses(java.instrument@11.0.11/InstrumentationImpl.java:193)
	at org.spongepowered.tools.agent.MixinAgent$Transformer.reApplyMixins(MixinAgent.java:121)
	at org.spongepowered.tools.agent.MixinAgent$Transformer.transform(MixinAgent.java:72)
	at java.lang.instrument.ClassFileTransformer.transform(java.instrument@11.0.11/ClassFileTransformer.java:246)
	at sun.instrument.TransformerManager.transform(java.instrument@11.0.11/TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(java.instrument@11.0.11/InstrumentationImpl.java:563)
```

**Comment by skybber** [comment]
What is the initiator of transform method? Is it redefinition in IDE? Why do you need call redefineClasses from transform? In case of HA we trigger redefinition e.g. of proxies in separate thread and since proxiesdepends on result of previous redefinion.

**Comment by DaMatrix** [comment]
It's initiated by the IDE, yes.

The agent is [Mixin](https://github.com/SpongePowered/Mixin), a framework for doing Java bytecode changes at runtime. These modifications are described using a "mixin" class, containing code which is injected into the target class. When `transform`-ing a mixin class, the javaagent is able to re-apply the transformations by using a saved copy of the target class' original bytecode, and then calls `redefineClasses` to update the target class. To the best of my knowledge there's no other way to implement this, as the target class isn't being redefined by the IDE (since from the IDE's perspective, the only thing that changed is the mixin class).

I can delay the redefinition of target classes by queuing them on a different thread, but that's bad for two reasons:
- There could be runtime errors if the old version of the target class references a member of some other class which was also removed, and would still be trying to access it before the second thread issues a reload
- There's no decent way (that I'm aware of) to detect when the IDE's redefinition is complete other than just setting the other thread to run after a fixed delay of some number of seconds. Redefining the classes from a different thread still causes a segfault if the initial reload is still running, so the only solution is to `sleep` for some number of seconds and hope it's enough (which is also needlessly slow).

**Comment by skybber** [comment]
I've added a lock to jvmti enhanced redefinition. Most likely it causes deadlock now if redefinition calls instrumentation transformer and it calls redefinition. Lock is necessary since we have use cases with redefinition triggered from multiple sources, advanced redefinition does a lot of preparation stuff  out of safepoint.

**Comment by skybber** [comment]
Unfortunately there is no "redefinition" event in jvmti. It would be great to create an extension for it, even it seems to not be so complicated and it would be helpful for HotswapAgent since it also depends on time delays. Also it would be nice to move this thread to HotswapAgent, since dcevm8 project is "EOL"
